/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\64885\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\_@vuepress_core@1.5.0@@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-109bd4d9",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-109bd4d9").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-4526e579",
    path: "/config/high/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4526e579").then(next)
    },
  },
  {
    path: "/config/high/index.html",
    redirect: "/config/high/"
  },
  {
    name: "v-1c5cd41b",
    path: "/config/base/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c5cd41b").then(next)
    },
  },
  {
    path: "/config/base/index.html",
    redirect: "/config/base/"
  },
  {
    name: "v-aef174a2",
    path: "/en/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aef174a2").then(next)
    },
  },
  {
    path: "/en/guide/index.html",
    redirect: "/en/guide/"
  },
  {
    name: "v-4b2ab15c",
    path: "/en/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b2ab15c").then(next)
    },
  },
  {
    path: "/en/index.html",
    redirect: "/en/"
  },
  {
    name: "v-7b5bda3c",
    path: "/en/config/high/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b5bda3c").then(next)
    },
  },
  {
    path: "/en/config/high/index.html",
    redirect: "/en/config/high/"
  },
  {
    name: "v-6b5c5948",
    path: "/en/config/base/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b5c5948").then(next)
    },
  },
  {
    path: "/en/config/base/index.html",
    redirect: "/en/config/base/"
  },
  {
    name: "v-7e6a2aec",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e6a2aec").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]