/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "文档管理",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicons/favicon-16x16.png",
        "type": "image/png",
        "sizes": "16x16"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/logo.png",
        "heroText": "文档管理",
        "tagline": "使用手册",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present xxxxxx"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-109bd4d9",
      "path": "/"
    },
    {
      "title": "高级配置",
      "frontmatter": {},
      "regularPath": "/config/high/",
      "relativePath": "config/high/README.md",
      "key": "v-4526e579",
      "path": "/config/high/",
      "headers": [
        {
          "level": 2,
          "title": "在加拿大吧",
          "slug": "在加拿大吧"
        },
        {
          "level": 3,
          "title": "库政府的",
          "slug": "库政府的"
        },
        {
          "level": 3,
          "title": "下班",
          "slug": "下班"
        },
        {
          "level": 2,
          "title": "时空裂缝不认识她呢",
          "slug": "时空裂缝不认识她呢"
        },
        {
          "level": 2,
          "title": "快乐主妇本土可直接回复本",
          "slug": "快乐主妇本土可直接回复本"
        },
        {
          "level": 3,
          "title": "考虑自己发的悲痛为",
          "slug": "考虑自己发的悲痛为"
        },
        {
          "level": 3,
          "title": "旅客在解放碑",
          "slug": "旅客在解放碑"
        },
        {
          "level": 2,
          "title": "旅客在解放碑陆家嘴",
          "slug": "旅客在解放碑陆家嘴"
        },
        {
          "level": 2,
          "title": "看到副本",
          "slug": "看到副本"
        }
      ]
    },
    {
      "title": "基本配置",
      "frontmatter": {},
      "regularPath": "/config/base/",
      "relativePath": "config/base/README.md",
      "key": "v-1c5cd41b",
      "path": "/config/base/",
      "headers": [
        {
          "level": 2,
          "title": "双方",
          "slug": "双方"
        },
        {
          "level": 3,
          "title": "看见幸福",
          "slug": "看见幸福"
        },
        {
          "level": 3,
          "title": "路西法",
          "slug": "路西法"
        },
        {
          "level": 2,
          "title": "家长反对",
          "slug": "家长反对"
        },
        {
          "level": 2,
          "title": "离开支付宝",
          "slug": "离开支付宝"
        },
        {
          "level": 3,
          "title": "离开自己的发表",
          "slug": "离开自己的发表"
        },
        {
          "level": 3,
          "title": "了空中打击犯罪吧",
          "slug": "了空中打击犯罪吧"
        }
      ]
    },
    {
      "title": "介绍en",
      "frontmatter": {},
      "regularPath": "/en/guide/",
      "relativePath": "en/guide/README.md",
      "key": "v-aef174a2",
      "path": "/en/guide/",
      "headers": [
        {
          "level": 2,
          "title": "展开在的en",
          "slug": "展开在的en"
        },
        {
          "level": 3,
          "title": "自动对焦en",
          "slug": "自动对焦en"
        },
        {
          "level": 2,
          "title": "最恐惧的",
          "slug": "最恐惧的"
        },
        {
          "level": 3,
          "title": "在DVD",
          "slug": "在dvd"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/logo.png",
        "heroText": "docs",
        "tagline": "guide",
        "actionText": "快速上手en →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present xxxxxx"
      },
      "regularPath": "/en/",
      "relativePath": "en/README.md",
      "key": "v-4b2ab15c",
      "path": "/en/"
    },
    {
      "title": "高级配置English",
      "frontmatter": {},
      "regularPath": "/en/config/high/",
      "relativePath": "en/config/high/README.md",
      "key": "v-7b5bda3c",
      "path": "/en/config/high/",
      "headers": [
        {
          "level": 2,
          "title": "在加拿大吧",
          "slug": "在加拿大吧"
        },
        {
          "level": 3,
          "title": "库政府的",
          "slug": "库政府的"
        },
        {
          "level": 3,
          "title": "下班",
          "slug": "下班"
        },
        {
          "level": 2,
          "title": "时空裂缝不认识她呢",
          "slug": "时空裂缝不认识她呢"
        },
        {
          "level": 2,
          "title": "快乐主妇本土可直接回复本",
          "slug": "快乐主妇本土可直接回复本"
        },
        {
          "level": 3,
          "title": "考虑自己发的悲痛为",
          "slug": "考虑自己发的悲痛为"
        },
        {
          "level": 3,
          "title": "旅客在解放碑",
          "slug": "旅客在解放碑"
        },
        {
          "level": 2,
          "title": "旅客在解放碑陆家嘴",
          "slug": "旅客在解放碑陆家嘴"
        },
        {
          "level": 2,
          "title": "看到副本",
          "slug": "看到副本"
        }
      ]
    },
    {
      "title": "基本配置English",
      "frontmatter": {},
      "regularPath": "/en/config/base/",
      "relativePath": "en/config/base/README.md",
      "key": "v-6b5c5948",
      "path": "/en/config/base/",
      "headers": [
        {
          "level": 2,
          "title": "双方",
          "slug": "双方"
        },
        {
          "level": 3,
          "title": "看见幸福",
          "slug": "看见幸福"
        },
        {
          "level": 3,
          "title": "路西法",
          "slug": "路西法"
        },
        {
          "level": 2,
          "title": "家长反对",
          "slug": "家长反对"
        },
        {
          "level": 2,
          "title": "离开支付宝",
          "slug": "离开支付宝"
        },
        {
          "level": 3,
          "title": "离开自己的发表",
          "slug": "离开自己的发表"
        },
        {
          "level": 3,
          "title": "了空中打击犯罪吧",
          "slug": "了空中打击犯罪吧"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-7e6a2aec",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "展开在的",
          "slug": "展开在的"
        },
        {
          "level": 3,
          "title": "自动对焦",
          "slug": "自动对焦"
        },
        {
          "level": 2,
          "title": "最恐惧的",
          "slug": "最恐惧的"
        },
        {
          "level": 3,
          "title": "在DVD",
          "slug": "在dvd"
        },
        {
          "level": 2,
          "title": "在在德国",
          "slug": "在在德国"
        },
        {
          "level": 2,
          "title": "脂肪酸哦",
          "slug": "脂肪酸哦"
        }
      ]
    }
  ],
  "themeConfig": {
    "search": false,
    "nextLinks": true,
    "prevLinks": true,
    "sidebar": [
      {
        "title": "组1",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/guide/"
        ]
      },
      {
        "title": "组2",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/config/base/",
          "/config/high/"
        ]
      }
    ],
    "sidebarDepth": 2,
    "navbar": true,
    "displayAllHeaders": true,
    "locales": {
      "/": {
        "selectText": "选择语言",
        "label": "简体中文",
        "nav": [
          {
            "text": "首页",
            "link": "/"
          },
          {
            "text": "指南",
            "link": "/guide/"
          },
          {
            "text": "配置",
            "items": [
              {
                "text": "基本配置",
                "link": "/config/base/"
              },
              {
                "text": "高级配置",
                "link": "/config/high/"
              }
            ]
          }
        ],
        "lastUpdated": "上次更新"
      },
      "/en/": {
        "selectText": "Languages",
        "label": "English",
        "nav": [
          {
            "text": "home",
            "link": "/en/"
          },
          {
            "text": "guide",
            "link": "/en/guide/"
          },
          {
            "text": "config",
            "items": [
              {
                "text": "base",
                "link": "/config/base/",
                "target": "_blank"
              },
              {
                "text": "high",
                "link": "/config/high/",
                "target": "_blank"
              }
            ]
          }
        ],
        "lastUpdated": "Last Updated"
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "文档管理",
      "description": "Vue 驱动的静态网站生成器",
      "path": "/"
    },
    "/en/": {
      "lang": "en-US",
      "title": "VuePress",
      "description": "Vue-powered Static Site Generator",
      "path": "/en/"
    }
  }
}